### ISSUE TITLE
your wiki is empty

### ISSUE THREAD

**Issue by jathagrimon** [2ndkauboy/textdomain-overwrite#6]
i think your intention is the same as mine (have read your blog in german) but i have problems to integrate your plugin into my wordpress.
Your documentation is to much minimized. ;-)

So i will tell my questions directly and hope you will answer soon and integrate the questions into your wiki.
1. Which files are needed ony .mo Files?
2. If yes, Who compiles the files? (if you use an external tool, tell us which one)
3. It is possible to add ONLY the content which will be added or manipulated write in the files? Or do i need the complete Original-.mo-File?
4. There is no BackendPage available for you plugin? Or i am blind? (Maybe it is not really needed, then ok)
5. I want to overwrite same translations in a Plugin which has his own .po .mo Files the folder is called like other-plugin. Now i have to use as filename other-plugin-de_DE.mo ? No problems with the minus in the name?

greetings

Jathagrimon

**Comment by 2ndkauboy** [comment]
You are right, that the documentation isn't the greates right now. I'll try to improve it with the next release.

Let's try to answer your questions in this issue:

1. Technically, WordPress only needs the .mo files, but as you can't edit them, it's a good idea to keep the .po files as well.
2. I use Poedit to compile the .mo files. Usually I take the the original files and remove all strings, I don't want to overwrite. If I only need a couple of overwrites, I use this file as a template for a new .po file: https://gist.github.com/2ndkauboy/87176ea646271f57f6f6
3. It is possible and you absolutely should do it this way. At all costs, you should avoid to copy the original .po file and just change some string. This would be a huge performace issue, as the plugin merges all files together.
4. There is no backend page, so you are not blind :) And indeed, there is no need for a backend page. The plugin works based on the folder structure described in the readme. Just name the folders and files as described and all the magic wil happen in the background.
5. The first version of the plugin was overwriting translastions based on a per plugin/theme folder structure. But as some plugins might share a textdomain or even use more than one textdomain, I changed the structure. Now you should name the files accoring to the textdomain, not the plugin/theme name. Let's take the plugin "PB oEmbed HTML5 Audio - with Cache Support" as an example. The plugin name is "pb-oembed-html5-audio-with-cache-support" but is uses the textdomain "PBoEmbedHTML5Audio". Therefore the files should be named "PBoEmbedHTML5Audio-de_DE.mo/.po".

I hope those answers will help you in getting a better understanding of how the plugin works. May I include them into the FAQ section in an upcoming version of the plugin?

**Comment by jathagrimon** [comment]
Thx 4 your quick response and your good answers.

2 last questions from my side:
1. Where i can find the textdomain if it is not the foldername of the plugin?
2. Into the .po Files exist normally a part like a header. If i want a own .po file in which i add only new strings i have to leave the header as it is and change only the whole entries?

greetings Jathagrimon

**Comment by 2ndkauboy** [comment]
1. For a plugin, search for a "lang" or "languages" folder. The po files in this folders should be prefixed with the textdomain. Other than that, you can may find the textdomain in the comment header of the main PHP file, the po file or as a second parameter of the different translation functions (https://codex.wordpress.org/I18n_for_WordPress_Developers).
2. You can just copy the original file including the header and change some bits (but you don't have to). Or just use the file from my first comment as a template.

**Comment by jathagrimon** [comment]
thanks, was working fine. 
Sorry for the late closing.
